version: "3.7"

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    command: /bin/bash -c "bin/setup.sh"
    ports:
      - "4567:4567"
    depends_on:
      - mongo
    volumes:
      - .:/smart_ac/api
    tty: true
    stdin_open: true

  admin:
    build: 
      context: ./admin
      dockerfile: Dockerfile.admin
    ports:
      - "3000:3000"
    volumes:
      - .:/smart_ac/admin
    depends_on:
      - api

  mongo:
    image: mongo:3.6-xenial
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo: {}
 